services:
  https:
    image: steveltn/https-portal:1
    ports:
      - '3443:443'
    environment:
      STAGE: local
      DOMAINS: 'localhost -> http://host.docker.internal:8000'
    depends_on:
      - db
  db:
    platform: linux/amd64
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: conspro2
      MYSQL_DATABASE: conspro2
      MYSQL_USER: conspro2
      MYSQL_PASSWORD: conspro2
      TZ: 'Asia/Tokyo'
    ports:
     - 3306:3306
    volumes:
     - data-volume:/var/lib/mysql
  web:
    container_name: conspro2
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/django
    ports:
      - "8000:8000"
    depends_on:
      - https

volumes:
 data-volume:
