# Generated by Django 3.2.19 on 2023-06-24 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='会社ID')),
                ('name', models.CharField(max_length=256, verbose_name='型式/MODE')),
                ('price', models.IntegerField(default=0, verbose_name='表示価格/LIST PRICE')),
                ('condition', models.CharField(choices=[('5', '5：新車もしくは、新車に近い状態'), ('4', '4：高年式・メーターの少ない極上品'), ('3', '3：現状で使用可能な状態'), ('2', '2：故障はしてないが、使用するには軽微な修理や整備が必要なもの'), ('1', '1：故障はしていないが、摩耗が激しく、使用するには相当の修理や整備が必要なもの'), ('B', 'B：エンジンや油圧系統など重要部品が故障しているもの')], default='5', max_length=2, verbose_name='程度/CONDITION RANK')),
                ('condition_maintenance', models.CharField(choices=[('1', '1：全塗装整備済み(Painted and Served)'), ('2', '2：整備済み(Served)'), ('3', '3：現状有姿(As is condition)')], default='1', max_length=2, verbose_name='整備状況/CONDITION MAINTENANCE')),
                ('year', models.CharField(blank=True, max_length=16, null=True, verbose_name='年式/YEAR')),
                ('serial_no', models.CharField(blank=True, max_length=256, null=True, verbose_name='号機')),
                ('hours', models.CharField(blank=True, max_length=16, null=True, verbose_name='稼働時間')),
                ('other', models.CharField(blank=True, max_length=256, null=True, verbose_name='DESCRIPTION')),
                ('other_ja', models.CharField(blank=True, max_length=256, null=True, verbose_name='詳細／仕様')),
                ('pic_url', models.CharField(blank=True, max_length=256, null=True, verbose_name='写真/PHOTO')),
                ('order_date', models.DateField(blank=True, null=True, verbose_name='発注日')),
                ('web_disp', models.BooleanField(default=False, verbose_name='WEB表示')),
                ('seller_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='仕入先名')),
                ('order_price', models.IntegerField(default=0, verbose_name='仕入価格')),
                ('order_trans_cost', models.IntegerField(default=0, verbose_name='仕入運賃')),
                ('parts_cost', models.IntegerField(default=0, verbose_name='部品代')),
                ('maintenance_cost', models.IntegerField(default=0, verbose_name='整備費')),
                ('order_out_order_cost', models.IntegerField(default=0, verbose_name='仕入外注費')),
                ('order_cost_price', models.IntegerField(default=0, verbose_name='仕入原価')),
                ('tran_place', models.CharField(blank=True, max_length=256, null=True, verbose_name='引渡場所')),
                ('sell_trance_cost', models.IntegerField(default=0, verbose_name='販売運賃')),
                ('ship_cost', models.IntegerField(default=0, verbose_name='船積費用')),
                ('sell_out_order_cost', models.IntegerField(default=0, verbose_name='販売外注費')),
                ('ins_cost', models.IntegerField(default=0, verbose_name='保険料')),
                ('freight_cost', models.IntegerField(default=0, verbose_name='フレイト')),
                ('sell_cost_price', models.IntegerField(default=0, verbose_name='販売原価')),
                ('sell_price', models.IntegerField(default=0, verbose_name='販売価格')),
                ('whol_price', models.IntegerField(default=0, verbose_name='業販価格')),
                ('profit', models.IntegerField(default=0, verbose_name='利益')),
                ('buyer_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='販売先名')),
                ('order_pay_date', models.DateField(blank=True, null=True, verbose_name='仕入代金支払日')),
                ('sell_pay_date', models.DateField(blank=True, null=True, verbose_name='売上入金日')),
                ('sell_month', models.DateField(blank=True, null=True, verbose_name='売上月')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='在庫メモ')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='仕入担当')),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_client', to='main.client', verbose_name='販売先')),
                ('creator', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_inventory', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('manufacturer', models.ForeignKey(db_column='maker_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.maker', verbose_name='メーカー/MANUFACTURER')),
                ('modifier', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='update_inventory', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_client', to='main.client', verbose_name='仕入先')),
                ('type', models.ForeignKey(db_column='machine_type_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.type_machine', verbose_name='分類')),
            ],
            options={
                'verbose_name': '在庫',
                'verbose_name_plural': '在庫',
            },
        ),
    ]
