# Generated by Django 3.2.19 on 2023-06-25 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='company',
            field=models.ForeignKey(db_column='company_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.company', verbose_name='会社'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='name',
            field=models.CharField(max_length=256, verbose_name='型式/MODEL'),
        ),
    ]
