# Generated by Django 3.2.19 on 2023-06-30 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20230625_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address_en',
            field=models.CharField(default=1, max_length=256, verbose_name='英語住所'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='fax_en',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='英語FAX番号'),
        ),
        migrations.AddField(
            model_name='company',
            name='name_en',
            field=models.CharField(default='test', max_length=256, verbose_name='英語会社名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='tel_en',
            field=models.CharField(default='test', max_length=16, verbose_name='英語電話番号'),
            preserve_default=False,
        ),
    ]
