# Generated by Django 3.2.19 on 2023-09-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_inventory_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='enrollment',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='在籍'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='price_day',
            field=models.IntegerField(default=0, verbose_name='日単価'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='price_month',
            field=models.IntegerField(default=0, verbose_name='月単価'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='price_support',
            field=models.IntegerField(default=0, verbose_name='サポート料金'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='size',
            field=models.IntegerField(default=0, verbose_name='サイズ（㎥）'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='weight',
            field=models.IntegerField(default=0, verbose_name='重量（㎏）'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='status',
            field=models.CharField(choices=[('0', '有効在庫'), ('1', '締め在庫'), ('2', 'レンタル空車'), ('3', 'レンタル出庫中'), ('5', 'その他'), ('6', '削除その他'), ('9', '削除在庫')], default='0', max_length=2, verbose_name='ステータス'),
        ),
    ]
