# Generated by Django 4.2.2 on 2024-05-12 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_work_alter_inventory_id_workrow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='other',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='other_ja',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='pic_url',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='web_disp',
        ),
        migrations.AddField(
            model_name='inventory',
            name='price_month_day',
            field=models.IntegerField(default=0, verbose_name='月極日単価'),
        ),
    ]
