# Generated by Django 4.2.2 on 2024-05-19 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_inventory_account_alter_inventory_buyer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalorderrow',
            name='memo',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='備考欄'),
        ),
        migrations.AddField(
            model_name='workrow',
            name='memo',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='備考欄'),
        ),
    ]
