# Generated by Django 4.2.2 on 2024-05-19 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_rentalorderrow_memo_workrow_memo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentalorder',
            options={'verbose_name': 'レンタル注文', 'verbose_name_plural': 'レンタル注文'},
        ),
    ]
