# Generated by Django 4.2.2 on 2024-05-19 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_rentalorder_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalorderrow',
            name='memo',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='備考欄'),
        ),
        migrations.AlterField(
            model_name='workrow',
            name='memo',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='備考欄'),
        ),
    ]
