# Generated by Django 4.2.2 on 2024-05-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_rentalorderrow_memo_alter_workrow_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalorder',
            name='close_date',
            field=models.CharField(choices=[('20', '20日'), ('30', '30日')], max_length=2, verbose_name='締め日'),
        ),
        migrations.AlterField(
            model_name='rentalorder',
            name='order_type',
            field=models.CharField(choices=[('0', '0：月極'), ('1', '1：日極')], max_length=2, verbose_name='注文区分'),
        ),
    ]
