# Generated by Django 4.2.2 on 2024-05-19 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_rentalorder_close_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalorder',
            name='request_date',
            field=models.DateField(blank=True, null=True, verbose_name='請求日'),
        ),
    ]
