# Generated by Django 4.2.2 on 2024-05-19 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_rentalorder_request_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalorderrow',
            name='is_out',
            field=models.BooleanField(default=True, verbose_name='出力'),
        ),
    ]
