# Generated by Django 4.2.2 on 2024-05-22 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_rentalorderrow_is_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrow',
            name='is_out',
            field=models.BooleanField(default=True, verbose_name='出力'),
        ),
    ]
