# Generated by Django 4.2.2 on 2024-05-27 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0021_workrow_is_out'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryOrderRow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='明細ID')),
                ('name', models.CharField(max_length=256, verbose_name='品目')),
                ('count', models.IntegerField(default=1, verbose_name='数量')),
                ('price', models.IntegerField(default=0, verbose_name='単価')),
                ('total', models.IntegerField(default=0, verbose_name='合計')),
                ('memo', models.CharField(blank=True, max_length=256, null=True, verbose_name='備考欄')),
                ('is_out', models.BooleanField(default=True, verbose_name='出力')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('creator', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_inventory_order_row', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_id', to='main.inventory')),
                ('modifier', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='update_inventory_order_row', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '在庫注文明細',
                'verbose_name_plural': '在庫注文明細',
            },
        ),
    ]
