# Generated by Django 4.2.2 on 2024-06-06 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_inventoryorderrow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='condition_maintenance',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='price',
        ),
    ]
