# Generated by Django 4.2.2 on 2024-06-21 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_inventory_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='status',
            field=models.CharField(choices=[('0', '有効在庫'), ('1', '締め在庫'), ('2', 'レンタル空車'), ('3', 'レンタル出庫中'), ('4', 'ユーザ機'), ('5', 'その他'), ('9', '削除')], default='0', max_length=2, verbose_name='ステータス'),
        ),
    ]
