# Generated by Django 4.2.2 on 2024-06-21 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_inventory_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='machine_name',
        ),
        migrations.RemoveField(
            model_name='work',
            name='serial_no',
        ),
        migrations.AddField(
            model_name='work',
            name='work_inventory',
            field=models.ForeignKey(db_column='inventory_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.inventory', verbose_name='機種-型-号機'),
        ),
    ]
